name: first workflow
on: workflow_dispatch
jobs:
 first-job:
  runs-on: ubuntu-latest
  steps:
    - name: print hello
      run: echo "Hello Action"
    - name: print end
      run: echo "Hello world ends"
